title: jekyllrb.github.io
description: the official unoffical jekyllrb collection
baseurl: "/"
url: http://jekyll.github.io
repository: jekyllrb.github.io
markdown: kramdown
github: 
 username: jekyllrb
 repository: jekyll.github.io
 branch: master
